# *** LOGIN PAGE ***
URL = "https://gene-nextjs-dev.dtskill.com/signin"
BROWSER = "chrome"
USERNAME = "varun.datt@dtskill.com"
PASSWORD = "123456"
VALID_PASSWORD = "123456"
USERNAME_LOCATOR = "xpath=/html/body/main/div/div/div/div[1]/div/div[2]/div[1]/form/div[1]/input"
PASSWORD_LOCATOR = "xpath=/html/body/main/div/div/div/div[1]/div/div[2]/div[1]/form/div[2]/input"
LOGIN_BUTTON = "xpath=/html/body/main/div/div/div/div[1]/div/div[2]/div[1]/form/button"
SUCCESS_URL = "https://gene-nextjs-dev.dtskill.com/dashboard"
LOGO_LOCATOR = "xpath=/html/body/main/div/div/div/div[1]/div/div[1]/img"
EMAIL_LOCATOR = "xpath=//input[@placeholder='Enter email address']"
EMAIL_LOGO = "xpath=//i[@class='fa-sharp fa-regular fa-envelope']"
EMAIL_TEXT_PRESENCE = "xpath=//input[@placeholder='Enter email address']"
PASSWORD_LOGO = "xpath=//i[@class='fa-sharp fa-regular fa-envelope']"
PASSWORD_TEXT = "xpath=//i[@class='fa-sharp fa-regular fa-lock']"
FORGOT_PASSWORD_PRESENCE = "xpath=//div[@class='forget-text']"
SIGN_IN_PRESENCE = "xpath=//button[normalize-space()='Sign In']"
SIGN_UP_PRESENCE = "xpath=//span[normalize-space()='Sign Up']"

# ***FORGOT PASSWORD PAGE***

FORGOT_PASSWORD_LINK = "xpath=/html/body/main/div/div/div/div[1]/div/div[2]/div[1]/form/div[3]/a/span"
GENE_LOGO_PRESENCE = "xpath=//img[@alt='sign-up logo']"
EMAIL_VERIFY_PRESENCE = "xpath=//div[normalize-space()='Email Verify']"
EMAIL_LOGO_IN_FORGOT_PASSWORD = "xpath=//i[@class='fa-sharp fa-regular fa-envelope']"
SEND_REST_LINK_IN_FORGOT_PASSWORD = "xpath=//button[normalize-space()='Send Reset Link']"
EMAIL_ADDRESS_IN_FORGOT_PASSWORD_PAGE = "xpath=//input[@placeholder='Enter email address']"
EMAIL_VERIFY_PAGE_URL = "https://gene-nextjs-dev.dtskill.com/email-verify"
EMAIL_INPUT = "xpath=/html/body/main/div/div/div/div[1]/div/div[3]/div/form/div/input"
SUBMIT_BUTTON = "xpath=/html/body/main/div/div/div/div[1]/div/div[3]/div/form/button"

# ***SIGNUP PAGE***
SIGN_UP_LINK_LOCATOR = "xpath=/html/body/main/div/div/div/div[1]/div/div[2]/div[2]/div/a/span"
SIGN_UP_PAGE_URL = "https://gene-nextjs-dev.dtskill.com/signup"
SIGN_UP_FIELDS_LOCATOR = "xpath=/html/body/main/div/div/div/div[1]/div/div[2]"
GENE_LOGO_IN_SIGNUP = "xpath=//img[@alt='sign-up logo']"
ENTER_YOUR_NAME_LOGO = "xpath=//i[@class='feather-user']"
BRIEFCASE_LOGO = "xpath=//i[@class='feather-briefcase']"
EMAIL_LOGO_IN_SIGNUP = "xpath=//i[@class='fa-sharp fa-regular fa-envelope']"
LOCK_LOGO_IN_SIGNUP = "xpath=//div[4]//div[1]//i[1]"
CONFIRM_PASSWORD_LOGO = "xpath=//div[4]//div[1]//i[1]"
SIGN_UP_BUTTON_PRESENCE_IN_SIGNUP = "xpath=//button[normalize-space()='Sign Up']"
SIGN_IN_PRESENCE_IN_SIGNUP = "xpath=//span[normalize-space()='Sign In']"
SIGN_UP_BUTTON = "xpath=/html/body/main/div/div/div/div[1]/div/div[2]/div[1]/form/button"
NAME_INPUT_LOCATOR = "xpath=/html/body/main/div/div/div/div[1]/div/div[2]/div[1]/form/div[1]/input"
EMAIL_INPUT_LOCATOR_IN_SIGNUP = "xpath=//input[@placeholder='Enter email address']"
CREATE_PASSWORD_IN_SIGNUP = "xpath=//input[@placeholder='Create Password']"
CONFIRM_PASSWORD_IN_SIGNUP = "xpath=//input[@placeholder='Confirm Password']"
VALID_NAME = "AnilKumarRahul"
VALID_EMAIL = "anil.kumar@dtskill.com"
ORG_ARROW_LOCATOR = "xpath=//*[@class='css-8mmkcg']"
ORG_DROPDOWN_LOCATOR = "xpath=//*[@class='css-8mmkcg']"
ORGANIZATION_OPTION_TEXT = "xpath=//div[@class=' css-19bb58m']"
CREATE_EMAIL_ADDRESS = "xpath=/html/body/main/div/div/div/div[1]/div/div[2]/div[1]/form/div[3]/input"
CREATE_PASSWORD = "xpath=/html/body/main/div/div/div/div[1]/div/div[2]/div[1]/form/div[4]/input"
CONFIRM_PASSWORD = "xpath=/html/body/main/div/div/div/div[1]/div/div[2]/div[1]/form/div[5]/input"
element_color_before_hover = "xpath=/html/body/main/div/header/div/div/div[2]/nav/ul/li[1]/a"
PYTHON_PATH = "python"
SCRIPT_PATH = "./send_report.py"
locator = "xpath=//nav[@class='mainmenu-nav d-none d-lg-block text-center']//a[@class='active'][normalize-space()='Home']"

# ***LANDING PAGE***

home_URL = "https://gene-nextjs-dev.dtskill.com/dashboard"
LOGO_LOCATOR_LANDING_PAGE = "xpath=/html/body/main/div/header/div/div/div[1]/div/div[2]/a/img"
TWO_OPTIONS_IN_LANDING_PAGE = "xpath=/html/body/main/div/header/div/div/div[2]/nav/ul"
HOME_OPTION_IN_LANDING_PAGE = "xpath=/html/body/main/div/header/div/div/div[2]/nav/ul/li[1]/a"
CONNECT_OPTION_IN_LANDING_PAGE = "xpath=/html/body/main/div/header/div/div/div[2]/nav/ul/li[2]/a"
USER_DP = "xpath=//div[@class='inner d-flex align-items-center']//img[@alt='user']"
USER_EMAIL_PRESENCE = "xpath=/html/body/main/div/header/div/div/div[3]/div/div[2]/div[1]"
USERNAME_PRESENCE = "xpath=//span[contains(@class,'title')]"
DASHBOARD_PRESENCE = "xpath=//div[@class='chat-box-section mt-60 table-container pt--20 pl--20']"

# *** YOUR PRIVATE GPT PAGE ***

SIDE_MENU = "xpath=/html/body/main/div/header/div/div/div[1]/div/div[1]/button/i"
PRIVATE_GPT = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[1]/a/span"
PRIVATE_GPT_IN_SUBPAGE = "xpath=//h6[normalize-space()='Private gpt']"
PRIVATE_GPT_LOGO_IN_SUBPAGE = "xpath=//img[@alt='Icon']"
E_LOGO_IN_GENE = "xpath=//span[normalize-space()='E']"
GENE_TEXT_IN_PRIVATE_GPT = "xpath=//div[@class='chat-content']//h6[@class='title']"
GENE_LOGO_IN_SUBPAGE_OF_PRIVATEGPT = "xpath=//img[@alt='Bot']"
OPTIONS_DROPDOWN_TOP_RIGHT_SIDE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[1]/div[2]/button/i"
REGENERATE_OPTION = "xpath=//i[@class='fa-sharp fa-solid fa-arrows-rotate']"
PIN_CHAT_OPTION = "xpath=//a[normalize-space()='Pin Chat']"
RENAME_OPTION = "xpath=//a[normalize-space()='Rename']"
SHARE_OPTION = "xpath=//a[normalize-space()='Share']"
DELETE_CHAT_OPTION = "xpath=//a[normalize-space()='Delete Chat']"
ASK_A_QUESTION_CONTAINER = "xpath=//textarea[@placeholder='Ask a question...']"
CAPTURE_LOGO_BESIDE_ASK_A_QUESTION = "xpath=//i[@class='fa-sharp fa-regular fa-aperture']"
CHOOSE_FILE_LOGO_OPTION = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[3]/div/div[2]/div/i"
SEND_QUESTION_LOGO_OPTION = "xpath=//i[@class='fa-sharp fa-solid fa-paper-plane-top']"
RIGHT_MENU = "xpath=/html/body/main/div/header/div/div/div[3]/div/div[3]/button"
NEW_CHAT = "xpath=/html/body/main/div/div[8]/div[1]/div"
SELECT_PLATFORM_AND_LLM_CONTAINER = "xpath=/html/body/main/div/div[8]/span[1]/div"
ARROW_OF_SELECT_PLATFORM_AND_LLM_CONTAINER = "xpath=/html/body/main/div/div[8]/span[1]/div/div/div[2]/div"
SELECT_ACCOUNT = "xpath=/html/body/main/div/div[8]/span[2]/div"
ARROW_OF_SELECT_ACCOUNT_CONTAINER = "xpath=/html/body/main/div/div[8]/span[2]/div/div/div[2]/div"
UPLOAD_DIRECTORY = "xpath=/html/body/main/div/div[8]/div[2]/a"
FILE_LOGO_OF_UPLOAD_DIRECTORY = "xpath=/html/body/main/div/div[8]/div[2]/a/span[1]/i"
UPLOAD_DIRECTORY_TEXT = "xpath=/html/body/main/div/div[8]/div[2]/a/span[2]"
UPLOAD_DIRECTORY_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/private-gpt/files"
FILE_TYPE_HEADING = "xpath=/html/body/main/div/div[8]/div/div[1]"
SELECT_TYPE_CONTAINER = "xpath=/html/body/main/div/div[8]/div/div[1]/div/span/div"
SELECT_TYPE_CONTAINER_ARROW = "xpath=/html/body/main/div/div[8]/div/div[1]/div/span/div/div/div[2]"
DOCX_OPTION = "xpath=//div[text()='DOCX']"
PDF_OPTION = "xpath=//div[text()='PDF']"
CSV_OPTION = "xpath=//div[text()='CSV']"
SELECT_DIRECTORY_TABLE = "xpath=/html/body/main/div/div[8]/div/div[2]"
SELECT_DIRECTORY_PAGE_NAVIGATOR = "xpath=/html/body/main/div/div[8]/div/div[3]/ul"
LEFT_NAVIGATOR_ARROW = "xpath=/html/body/main/div/div[8]/div/div[3]/ul/li[1]"
RIGHT_NAVIGATOR_ARROW = "xpath=/html/body/main/div/div[8]/div/div[3]/ul/li[3]/a"
FIRST_PAGE_INDICATOR = "xpath=/html/body/main/div/div[8]/div/div[3]/ul/li[2]"
SECOND_PAGE_INDICATOR = "xpath=/html/body/main/div/div[8]/div/div[3]/ul/li[3]"

# ***ChatgptAlternate Page ***
SIDEMENU_OPTIONS = "xpath=/html/body/main/div/div[1]/div/div[1]"
SUBCRIPTION_BOX = "xpath=/html/body/main/div/div[1]/div/div[2]"
USERIMAGE_IN_SUBCRIPTION_BOX = "xpath=/html/body/main/div/div[1]/div/div[2]/div/a/div[1]/img"
USERNAME_IN_SUBCRIPTION_BOX = "xpath=/html/body/main/div/div[1]/div/div[2]/div/a/div[2]"
CHAT_GPT_ALTERNATE_BOX = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/a"
CHAP_GPT_ALTERNATE_BOX_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/a/img"
CHAT_GPT_ALTERNATE_BOX_ARROW = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/a"
OPTIONS_IN_CHATGPT_ALTERNATE = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div"
CHAT_WITH_DOCS = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[1]/a"
CHAT_WITH_DOCS_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[1]/a/img"
CHAT_WITH_DOCS_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/chat-with-docs"
CHAT_WITH_DOCS_IN_SUBPAGE = "xpath=//h6[normalize-space()='Chat with Docs']"
CHAT_WITH_DOCS_LOGO_IN_SUBPAGE = "xpath=//img[@alt='Icon']"
DROPDOWN = "xpath=//div[contains(@class,'css-1lejkn2f-control')]"
GPT4_TURBO_OPTION = "xpath=//div[text()='GPT-4 Turbo']"
GPT4o_OPTION = "xpath=//div[text()='GPT-4o']"
GPT4o_mini_OPTION = "xpath=//div[text()='GPT-4o mini']"
Anyscale_Mistral_Option = "xpath=//div[text()='Anyscale Mistral']"
Anyscale_Llama_Option = "xpath=//div[text()='Anyscale Llama']"
Groq_Mistral_Option = "xpath=//div[text()='Groq Mistral']"
Groq_Llama3_8b_Option = "xpath=//div[text()='Groq Llama3 8b']"
Groq_Llama3_70b_Option = "xpath=//div[text()='Groq Llama3 70b']"
DT_skill_OPTION = "xpath=//div[text()='DTskill']"
Sandbox_OPTION = "xpath=//div[text()='Sandbox']"
Your_Account_OPTION = "xpath=//div[text()='Your Account']"
CHAT_WITH_CODE = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[2]/a"
CHAT_WITH_CODE_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[2]/a/img"
CHAT_WITH_CODE_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/chat-with-code"
CHAT_WITH_CODE_IN_SUBPAGE = "xpath=//h6[normalize-space()='Chat with Code']"
CHAT_WITH_CODE_LOGO_IN_SUBPAGE = "xpath=//img[@alt='Icon']"
HISTORY = "xpath=/html/body/main/div/div[8]/div[2]/div"
CHAT_WITH_SCRIPT = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[3]/a"
CHAT_WITH_SCRIPT_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[3]/a/img"
CHAT_WITH_SCRIPT_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/chat-with-script"
CHAT_WITH_SCRIPT_IN_SUBPAGE = "xpath=//h6[normalize-space()='Chat With Script']"
CHAT_WITH_SCRIPT_LOGO_IN_SUBPAGE = "xpath=//img[@alt='Icon']"
CHAT_WITH_LOG = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[4]/a"
CHAT_WITH_LOG_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[4]/a/img"
CHAT_WITH_LOG_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/chat-with-log"
CHAT_WITH_LOG_IN_SUBPAGE = "xpath=//h6[normalize-space()='Chat with Log']"
CHAT_WITH_LOG_LOGO_IN_SUBPAGE = "xpath=//img[@alt='Icon']"
BUFFER_MEMORY = "xpath=//a[@href='/dashboard/buffer-memory']"
BUFFER_MEMORY_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[5]/a/img"
BUFFER_MEMORY_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/buffer-memory"
BUFFER_MEMORY_IN_SUBPAGE = "xpath=//h6[normalize-space()='Buffer Memory']"
BUFFER_MEMORY_LOGO_IN_SUBPAGE = "xpath=//img[@alt='Icon']"
SUMMARY_BUFFER = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[6]/a"
SUMMARY_BUFFER_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[6]/a/img"
SUMMARY_BUFFER_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/summary-buffer"
SUMMARY_BUFFER_IN_SUBPAGE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[1]/div[1]/h6"
SUMMARY_BUFFER_LOGO_IN_SUBPAGE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[1]/div[1]/div"
CHAT_WITH_MF4 = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[7]/a"
CHAT_WITH_MF4_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[6]/a/img"
CHAT_WITH_MF4_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/chat-with-mf4"
CHAT_WITH_MF4_IN_SUBPAGE = "xpath=//h6[normalize-space()='Chat With MF4']"
CHAT_WITH_MF4_LOGO_IN_SUBPAGE = "xpath=//img[@alt='Icon']"
DEPARTMENT = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[8]/a"
DEPARTMENT_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[7]/a/img"
DEPARTMENT_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/department"
DEPARTMENT_IN_SUBPAGE = "xpath=//h6[normalize-space()='Department']"
DEPARTMENT_LOGO_IN_SUBPAGE = "xpath=//img[@alt='Icon']"
VOICE_ASSISTANT = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[9]/a"
VOICE_ASSISTANT_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[2]/div/ul/li[8]/a/img"
VOICE_ASSISTANT_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/voice-assistant"
VOICE_ASSISTANT_IN_SUBPAGE = "xpath=//h6[normalize-space()='Voice Assistant']"
VOICE_ASSISTANT_LOGO_IN_SUBPAGE = "xpath=//img[@alt='Icon']"

# *** Fine-Tuned Models Email Classification Page ***
FINE_TUNED_MODELS_BOX = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[3]/a"
FINE_TUNED_MODELS_BOX_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[3]/a/img"
OPTIONS_IN_FINE_TUNED_MODELS = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[3]/div/ul"
EMAIL_FUNCTIONALITY = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[3]/div/ul/li[1]/a"
EMAIL_FUNCTIONALITY_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[3]/div/ul/li[1]/a/img"
EMAIL_FUNCTIONALITY_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/email-classification"
TEXT_AREA = "xpath=//textarea[@id='Textarea']"
INPUT_TEXT = "xpath=//h5[normalize-space()='Input']"
RUN_BUTTON = "xpath=//button[normalize-space()='Run']"
OUTPUT_TEXT = "xpath=//h5[normalize-space()='Output']"
LLM_DEPLOYMENT_DROPDOWN = "xpath=/html/body/main/div/div[8]/div[2]/div/span/div/div"
LLM_DEPLOYMENT_DROPDOWN_ARROW = "xpath=/html/body/main/div/div[8]/div[2]/div/span/div/div/div[2]"
Mistral_7b_Instruct_Option = "xpath=//div[contains(text(),'Mistral 7b Instruct')]"
Llama_2_7b_Chat_Option = "xpath=//div[contains(text(),'Llama 2 7b Chat')]"
Anyscale_Llama_option = "xpath=//div[contains(text(),'Anyscale Llama')]"
Gemma_7_Instruct_Option = "xpath=//div[contains(text(),'Gemma7 Instruct')]"

# *** Fine-Tuned Models Decoding Page ***
DECODING_BOX = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[3]/div/ul/li[2]/a"
DECODING_BOX_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[3]/div/ul/li[2]/a/img"
DECODING_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/decoding"

# *** ESB NOTES ACTION TAGGING Page ***
ESB_NOTES_ACTION_TAGGING_BOX = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[3]/div/ul/li[3]/a"
ESB_NOTES_ACTION_TAGGING_BOX_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[3]/div/ul/li[3]/a/img"
ESB_NOTES_ACTION_TAGGING_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/esb"

# *** CUSTOM ML MODELS Page ***
CUSTOM_ML_MODELS_BOX = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[4]/a"
CUSTOM_ML_MODELS_BOX_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[4]/a/img"
SAFE_DIGGING_BOX = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[4]/div"
SAFE_DIGGING_BOX_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[4]/div/ul/li/a/img"
SAFE_DIGGING_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/safe-digging"
DRAG_AND_DROP_OR_SELECT_A_PDF_TO_UPLOAD_BOX = "xpath=/html/body/main/div/div[8]/div/div[1]/div[1]/div"
DRAG_AND_DROP_OR_SELECT_A_PDF_TO_UPLOAD_BOX_LOGO = "xpath=/html/body/main/div/div[8]/div/div[1]/div[1]/div/i"
DRAG_AND_DROP_OR_SELECT_A_PDF_TO_UPLOAD_BOX_TEXT = "xpath=/html/body/main/div/div[8]/div/div[1]/div[1]/div/span"
SELECT_COMPANY_BOX = "xpath=/html/body/main/div/div[8]/div/div[1]/div[2]/span/div/div"
SELECT_COMPANY_BOX_ARROW = "xpath=/html/body/main/div/div[8]/div/div[1]/div[2]/span/div/div/div[2]"
SGN_OPTION = "xpath=//div[contains(text(),'SGN')]"
WWU_OPTION = "xpath=//div[contains(text(),'WWU')]"
NGN_OPTION = "xpath=//div[contains(text(),'NGN')]"
CADENT_GAS_OPTION = "xpath=//div[contains(text(),'CadentGas')]"
UPLOAD_BUTTON = "xpath=/html/body/main/div/div[8]/div/div[1]/div[3]"
TABLE_PRESENCE = "xpath=/html/body/main/div/div[8]/div/div[2]/table"
EXPECTED_COLUMN1 = "Job Reference"
EXPECTED_COLUMN2 = "Utility Provider"
EXPECTED_COLUMN3 = "Red Line"
EXPECTED_COLUMN4 = "Blue Line"
EXPECTED_COLUMN5 = "Green Line"
EXPECTED_COLUMN6 = "Orange Line"
EXPECTED_COLUMN7 = "Job Ready for Release"
EXPECTED_COLUMN8 = "Image Validation"
EXPECTED_COLUMN9 = "Warning Validation"
EXPECTED_COLUMN10 = "Critical Line"
EXPECTED_COLUMN11 = "Warning Indicator"
EXPECTED_COLUMN12 = "Warning Message"
EXPECTED_COLUMN13 = "Created Date"
EXPECTED_COLUMN14 = "Modified Date"
LEFT_ARROW = "xpath=/html/body/main/div/div[8]/div/div[3]/ul/li[1]/a"
RIGHT_ARROW = "xpath=/html/body/main/div/div[8]/div/div[3]/ul/li[3]/a"
PAGE_NUMBER = "xpath=/html/body/main/div/div[8]/div/div[3]/ul/li[2]/a"
SCROLL_BAR = "xpath=//div[@class='chat-box-section mt-60 table-container']"

# *** SALESFORCE KB EXPLORER PAGE IN AI AGENTS ***
AI_AGENTS_BOX = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[5]/a"
AI_AGENTS_BOX_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[5]/a/img"
OPTIONS_IN_AI_AGENTS_BOX = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[5]/div"
SALESFORCE_KB_EXPLORER_BOX = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[5]/div/ul/li[1]/a"
SALESFORCE_KB_EXPLORER_BOX_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[5]/div/ul/li[1]/a/img"
SALESFORCE_KB_EXPLORER_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/salesforce-kb-explorer"
SUBPAGE_IN_SALESFORCE_KB_EXPLORER_PAGE = "xpath=/html/body/main/div/div[9]/div/div/div/div"
SALESFORCE_KB_EXPLORER_TEXT_IN_WHITE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[1]/div[1]/h6"
SALESFORCE_KB_EXPLORER_LOGO_IN_SUBPAGE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[1]/div[1]/div/img"
ASK_A_QUESTION_TEXT = "xpath=//textarea[@placeholder='Ask a question...']"

# *** HANDWRITTEN OCR PAGE IN AI AGENTS ***
HANDWRITTEN_OCR_BOX = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[5]/div/ul/li[2]/a"
HANDWRITTEN_OCR_BOX_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[5]/div/ul/li[2]/a/img"
HANDWRITTEN_OCR_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/hand-written-ocr"
SUBPAGE_IN_HANDWRITTEN_OCR_PAGE = "xpath=/html/body/main/div/div[8]/div"
UPLOAD_IMAGE_HEADING_IN_SUBPAGE = "xpath=/html/body/main/div/div[8]/div/div[1]/div[1]/h5"
LATEX_OUTPUT_TEXT_IN_SUBPAGE = "xpath=/html/body/main/div/div[8]/div/div[2]/div[1]/h6"
LATEX_OUTPUT_CONTAINER = "xpath=/html/body/main/div/div[8]/div/div[2]/div[1]/textarea"
RENDERED_OUTPUT_TEXT_IN_SUBPAGE = "xpath=/html/body/main/div/div[8]/div/div[2]/div[2]/h6"
UPLOAD_BUTTON_IN_SUBPAGE = "xpath=/html/body/main/div/div[8]/div/div[1]/div[1]/div[2]/div[2]/button"
UPLOADED_IMAGE_TEXT_IN_SUBPAGE = "xpath=/html/body/main/div/div[8]/div/div[1]/div[2]/h6"
uploaded_an_image_TEXT_IN_SUBPAGE = "xpath=/html/body/main/div/div[8]/div/div[1]/div[2]/div"
UPLOAD_IMAGE_CONTAINER = "xpath=/html/body/main/div/div[8]/div/div[1]/div[1]/div[2]/div[1]"
UPLOAD_IMAGE_LOGO_IN_CONTAINER = "xpath=/html/body/main/div/div[8]/div/div[1]/div[1]/div[2]/div[1]/i"
TEXT_IN_UPLOAD_IMAGE_CONTAINER = "xpath=/html/body/main/div/div[8]/div/div[1]/div[1]/div[2]/div[1]/span"

# *** EMAIL EXTRACTION IN AI AGENTS ***
EMAIL_EXTRACTION_BOX = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[5]/div/ul/li[4]/a"
EMAIL_EXTRACTION_BOX_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[5]/div/ul/li[4]/a/img"
EMAIL_EXTRACTION_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/email-extraction"

# *** SAI SCRIPT-DEMO PAGE IN AI AGENTS ***
SAI_SCRIPT_DISTRO_BOX = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[5]/div/ul/li[5]/a"
SAI_SCRIPT_DISTRO_BOX_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[5]/div/ul/li[5]/a/img"
SAI_SCRIPT_DISTRO_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/sai-script-distro"
SAI_SCRIPT_DISTRO_SUBPAGE = "xpath=/html/body/main/div/div[8]/div/div/div/div"
SAI_BATCHWISE_SCRIPT_ALLOCATION_HEADING_IN_SUBPAGE = "xpath=/html/body/main/div/div[8]/div/div/div/div/div/div/h4"
LO_SOURCE_GOOGLE_SHEET_LINK_TEXT = "xpath=/html/body/main/div/div[8]/div/div/div/div/div/form/div[1]/div/label"
LO_SOURCE_GOOGLE_SHEET_LINK_CONTAINER = "xpath=/html/body/main/div/div[8]/div/div/div/div/div/form/div[1]/div/textarea"
LO_SOURCE_PPT_GOOGLE_SHEET_LINK_TEXT = "xpath=/html/body/main/div/div[8]/div/div/div/div/div/form/div[2]/div/label"
LO_SOURCE_PPT_GOOGLE_SHEET_LINK_CONTAINER = "xpath=/html/body/main/div/div[8]/div/div/div/div/div/form/div[2]/div/textarea"
LO_START_ROW_TEXT = "xpath=/html/body/main/div/div[8]/div/div/div/div/div/form/div[3]/div/label"
LO_START_ROW_CONTAINER = "xpath=/html/body/main/div/div[8]/div/div/div/div/div/form/div[3]/div/input"
LO_END_ROW_TEXT = "xpath=/html/body/main/div/div[8]/div/div/div/div/div/form/div[4]/div/label"
LO_END_ROW_CONTAINER = "xpath=/html/body/main/div/div[8]/div/div/div/div/div/form/div[4]/div/input"
DESTINATION_FOLDER_TEXT = "xpath=/html/body/main/div/div[8]/div/div/div/div/div/form/div[5]/div/label"
DESTINATION_FOLDER_CONTAINER = "xpath=/html/body/main/div/div[8]/div/div/div/div/div/form/div[5]/div/input"
SUBMIT_BUTTON_IN_SAI_SCRIPT_DISTRO_SUBPAGE = "xpath=/html/body/main/div/div[8]/div/div/div/div/div/form/div[6]/div/button"

# *** LLM METRICS LLM PERFORMANCE PAGE
LLM_METRICS_BOX = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[6]/a"
LLM_METRICS_BOX_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[6]/a/img"
LLM_PERFORMANCE_BOX = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[6]/div/ul/li[1]/a"
LLM_PERFORMANCE_BOX_LOGO = "xpath=/html/body/main/div/div[1]/div/div[1]/div/div/nav/div[1]/ul/li[6]/div/ul/li[1]/a/img"
LLM_PERFORMANCE_URL = "https://gene-nextjs-dev.dtskill.com/dashboard/llm-metrics"
LLM_PERFORMANCE_TABLE = "xpath=/html/body/main/div/div[8]/div/div[1]"
COLUMN1_IN_LLM_PERFORMANCE_TABLE = "Application"
COLUMN2_IN_LLM_PERFORMANCE_TABLE = "Question"
COLUMN3_IN_LLM_PERFORMANCE_TABLE = "Response"
COMPLETENESS_IN_COLUMN3 = "Completeness"
CONSISTENCY_IN_COLUMN3 = "Consistency"
RELEVANCE_IN_COLUMN3 = "Relevance"
VALIDITY_IN_COLUMN3 = "Validity"
CONCISENESS_IN_COLUMN3 = "Conciseness"
COLUMN4_IN_LLM_PERFORMANCE_TABLE = "Code Hallucination"
COLUMN5_IN_LLM_PERFORMANCE_TABLE = "Context"
UTILIZATION_IN_COLUMN5 = "Utilization"
ACCURACY_IN_COLUMN5 = "Accuracy"
RELEVANCE_IN_COLUMN5 = "Relevance"
COLUMN6_IN_LLM_PERFORMANCE_TABLE = "Fluency"
COLUMN7_IN_LLM_PERFORMANCE_TABLE = "Coherence"
COLUMN8_IN_LLM_PERFORMANCE_TABLE = "Grammar"
COLUMN9_IN_LLM_PERFORMANCE_TABLE = "Politeness"
LEFT_ARROW_KEY = "xpath=/html/body/main/div/div[8]/div/div[2]/ul/li[1]/a"
PAGE_NUMBER1_OF_TABLE = "xpath=/html/body/main/div/div[8]/div/div[2]/ul/li[2]/a"
PAGE_NUMBER2_OF_TABLE = "xpath=/html/body/main/div/div[8]/div/div[2]/ul/li[3]/a"
PAGE_NUMBER3_OF_TABLE = "xpath=/html/body/main/div/div[8]/div/div[2]/ul/li[4]/a"
PAGE_NUMBER4_OF_TABLE = "xpath=/html/body/main/div/div[8]/div/div[2]/ul/li[5]/a"
RIGHT_ARROW_KEY = "xpath=/html/body/main/div/div[8]/div/div[2]/ul/li[6]/a"
SUMMARY_BOX_POPUP = "xpath=/html/body/main/div/div[8]/div/div[1]/table/tbody/tr[1]/td[1]"
EMAIL_DETAILS_IN_POPUP = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[1]"
APPLICATION_DETAILS_IN_POPUP = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[2]"
QUESTION_DETAILS_IN_POPUP = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[3]"
RESPONSE_COMPLETENESS_DETAILS_IN_POPUP = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[4]/h5"
SCORE_DETAILS_IN_POPUP = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[4]/div/div[1]"
EXPLANATION_DETAILS_IN_POPUP = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[4]/div/div[2]"
RESPONSE_CONSISTENCY_IN_POPUP = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[5]"
SCORE_IN_RESPONSE_CONSISTENCY = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[5]/div/div[1]"
EXPLANATION_IN_RESPONSE_CONSISTENCY = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[5]/div/div[2]"
RESPONSE_RELEVANCE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[6]/h5"
SCORE_IN_RESPONSE_RELEVANCE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[6]/div/div[1]"
EXPLANATION_IN_RESPONSE_RELEVANCE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[6]/div/div[2]"
VALID_RESPONSE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[7]"
SCORE_IN_VALID_RESPONSE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[7]/div/div[1]"
EXPLANATION_DETAILS_IN_VALID_RESPONSE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[7]/div/div[2]"
RESPONSE_CONCISENESS = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[8]/h5"
SCORE_IN_RESPONSE_CONCISENESS = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[8]/div/div[1]"
EXPLANATION_IN_RESPONSE_CONCISENESS = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[8]/div/div[2]"
CONTEXT_UTILISATION = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[9]/h5"
SCORE_IN_CONTEXT_UTILISATION = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[9]/div/div[1]"
EXPLANATION_IN_CONTEXT_UTILISATION = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[9]/div/div[2]"
FACTUAL_ACCURACY = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[10]/h5"
SCORE_IN_FACTUAL_ACCURACY = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[10]/div/div[1]"
EXPLANATION_IN_FACTUAL_ACCURACY = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[10]/div/div[2]"
CODE_HALLUCINATION = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[11]/h5"
SCORE_IN_CODE_HALLUCINATION = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[11]/div/div[1]"
EXPLANATION_IN_CODE_HALLUCINATION = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[11]/div/div[2]"
CONTEXT_RELEVANCE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[12]/h5"
SCORE_IN_CONTEXT_RELEVANCE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[12]/div/div[1]"
EXPLANATION_IN_CONTEXT_RELEVANCE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[12]/div/div[2]"
FLUENCY = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[13]/h5"
SCORE_IN_FLUENCY = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[13]/div/div[1]"
EXPLANATION_IN_FLUENCY = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[13]/div/div[2]"
COHERENCE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[14]/h5"
SCORE_IN_COHERENCE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[14]/div/div[1]"
EXPLANATION_IN_COHERENCE = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[14]/div/div[2]"
GRAMMAR = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[15]/h5"
SCORE_IN_GRAMMAR = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[15]/div/div[1]"
EXPLANATION_IN_GRAMMAR = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[15]/div/div[2]"
POLITENESS = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[16]/h5"
SCORE_IN_POLITENESS = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[16]/div/div[1]"
EXPLANATION_IN_POLITENESS = "xpath=/html/body/main/div/div[9]/div/div/div/div/div[16]/div/div[2]"
CLOSE_BUTTON_OF_POPUP = "xpath=/html/body/main/div/div[9]/div/div/button"
SCROLLABLE_ELEMENT = "xpath=/html/body/main/div/div[9]/div/div"



